SELECT
MAX(IF(OCCUPATION = "DOCTOR",NAME,NULL)) AS DOCTOR,
MAX(IF(OCCUPATION = "PROFESSOR",NAME,NULL)) AS PROFESSOR,
MAX(IF(OCCUPATION = "SINGER",NAME,NULL)) AS SINGER,
MAX(IF(OCCUPATION = "ACTOR",NAME,NULL)) AS ACTOR

FROM

(SELECT NAME, OCCUPATION, ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS ROW_NUM FROM OCCUPATIONS) AS ORD GROUP BY ROW_NUM;